const ADD_USER = 'ADD_USER'
const DELETE_USER = 'DELETE_USER'
const EDIT_USER = 'EDIT_USER'
const UPDATE_USER = 'UPDATE_USER'


export default {
    ADD_USER,
    DELETE_USER,
    EDIT_USER,
    UPDATE_USER
}